:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

# 運用

## NPMスクリプトとは

npmスクリプトは、package.jsonファイルに記述された、npmコマンドのショートカットです。npmスクリプトを使用すると、npmコマンドを簡単に実行できます。

開発中のWebアプリケーションを構築するために使用するモジュール群です。以下でそれぞれの役割を説明します。

- npm-run-all: 複数のnpm scriptコマンドを同時に実行したり、シーケンシャルに実行したりすることができるパッケージです。
- cpx: ファイルのコピーを簡単に実行することができるツールです。
- rimraf: ファイルやディレクトリを削除するためのパッケージです。通常、rm -rfの代替手段として使用されます。

これらのツールを使用することで、エラーハンドリングやファイル操作などを簡単に処理することができます。特に、npm run scriptにおいて便利な機能を提供します。

```
npm install --save-dev npm-run-all cpx rimraf
```

## Gulpとは

GulpはJavaScriptのタスクランナーで、自動化されたビルドプロセスを作成することができます。

Gulpを使用すると、SassまたはLessファイルをコンパイルし、画像を最適化したり、JavaScriptを圧縮したりするなど、いくつかのタスクを自動化できます。

以下はGulpを使用する基本的な手順です

Node.jsをインストールします。

ターミナルで、プロジェクトフォルダに移動して npm init を実行して、 package.json ファイルを作成します。

Gulpをインストールします

```
npm install --save-dev gulp
```

Gulpタスクを作成します

プロジェクトフォルダに gulpfile.js ファイルを作成します。ここに、必要なモジュールをロードするコードと、各タスクを定義するコードを書きます。
例えば、CSSファイルをコンパイルするタスクを以下のように定義することができます

```
const gulp = require('gulp');
const sass = require('gulp-sass');

gulp.task('sass', function () {
  return gulp.src('./sass/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest('./css'));
});

gulp.task('watch', function () {
  gulp.watch('./sass/**/*.scss', ['sass']);
});
```

タスクを実行します

ターミナルで、 gulp タスク名 を入力して、タスクを実行します。例えば、上記のタスクを実行するには、 gulp sass と入力します。
これでGulpを使用して、独自のタスクを作成し、シンプルでエレガントなビルドプロセスを実現できます。

## Asciidocとは

Assciidoctorは、Rubyで書かれたドキュメント変換ツールです。Markdownとは異なり、Asciidoctorは、ドキュメントの構造を表すために、マークアップ言語を使用します。

```
npm install --save-dev asciidoctor asciidoctor-kroki
```

`docs` ディレクトリに `index.adoc` ファイルを作成し、以下の内容を記述します。

```asciidoc
:toc: left
:toclevels: 5
:sectnums:

= Asciidoc

== 目的

== 前提

== 構成
* <<anchor-1,サンプル>>

== 詳細
=== link:./sample.html[サンプル^][[anchor-1]]

== 参照
```

gulpタスクを作成します。

```js
const { series } = require("gulp");
const { default: rimraf } = require("rimraf");

const asciidoctor = {
  clean: async (cb) => {
    await rimraf("./public/docs");
    cb();
  },
  build: (cb) => {
    const fs = require("fs");
    const asciidoctor = require("@asciidoctor/core")();
    const kroki = require("asciidoctor-kroki");

    const krokiRegister = () => {
      const registry = asciidoctor.Extensions.create();
      kroki.register(registry);
      return registry;
    };

    const inputRootDir = "./docs";
    const outputRootDir = "./public/docs";
    const fileNameList = fs.readdirSync(inputRootDir);
    const docs = fileNameList.filter(RegExp.prototype.test, /.*\.adoc$/);

    docs.map((input) => {
      const file = `${inputRootDir}/${input}`;
      asciidoctor.convertFile(file, {
        safe: "safe",
        extension_registry: krokiRegister(),
        to_dir: outputRootDir,
        mkdirs: true,
      });
    });
    cb();
  },
  watch: (cb) => {
    watch("./docs/**/*.adoc", asciidoctor.build);
    cb();
  },
}

exports.docs = series(asciidoctor.clean, asciidoctor.build);
```

gulpタスクを実行します。

```
npx gulp docs
```

npmタスクに追加します。

```json
{
  "scripts": {
    "docs": "gulp docs"
  }
}
```

## BrowserSyncとは

BrowserSyncは、開発中のWebアプリケーションを構築するために使用するモジュール群です。以下でそれぞれの役割を説明します。

インストールします。

```
npm install --save-dev browser-sync
```

`gulpfile.js` に以下の内容を追加します。

```js
const { series } = require("gulp");
const { default: rimraf } = require("rimraf");
const browserSync = require('browser-sync').create();

const asciidoctor = {
  clean: async (cb) => {
    await rimraf("./public/docs");
    cb();
  },
  build: (cb) => {
    const fs = require("fs");
    const asciidoctor = require("@asciidoctor/core")();
    const kroki = require("asciidoctor-kroki");

    const krokiRegister = () => {
      const registry = asciidoctor.Extensions.create();
      kroki.register(registry);
      return registry;
    };

    const inputRootDir = "./docs";
    const outputRootDir = "./public/docs";
    const fileNameList = fs.readdirSync(inputRootDir);
    const docs = fileNameList.filter(RegExp.prototype.test, /.*\.adoc$/);

    docs.map((input) => {
      const file = `${inputRootDir}/${input}`;
      asciidoctor.convertFile(file, {
        safe: "safe",
        extension_registry: krokiRegister(),
        to_dir: outputRootDir,
        mkdirs: true,
      });
    });
    cb();
  },
  watch: (cb) => {
    watch("./docs/**/*.adoc", asciidoctor.build);
    cb();
  },
  server: (cb) => {
    browserSync.init({
      server: {
        baseDir: "./public",
      },
    });
    watch("./public/**/*.html").on("change", browserSync.reload);
    cb();
  },
}

exports.docs = series(asciidoctor.clean, asciidoctor.build, asciidoctor.server);
```

## Marpとは

Marpは、Markdownでスライドを作成するためのツールです。以下でそれぞれの役割を説明します。

インストールします。

```bash
npm install --save-dev @marp-team/marp-cli
```

スライドを作成します。

`docs/slides` ディレクトリに `PITCHME.md` ファイルを作成し、以下の内容を記述します。

```markdown
---
marp: true
---

### タイトル

---

### 構成

- 自己紹介
- トピック 1
- トピック 2
- トピック 3

---

### 自己紹介

---

### トピック 1

---

### トピック 2

---

### トピック 3

---

### おわり

---

### 参照

---
```

スライドをビルドします。

```bash
npx marp --html --allow-local-files ../docs/slides/PITCHME.md
```

gulpタスクを作成します。

```js
marp = {
  build: (cb) => {
    const { marpCli } = require('@marp-team/marp-cli')

    marpCli(['./docs/slides/PITCHME.md', '--html', '--output', './public/slides/index.html'])
      .then((exitStatus) => {
        if (exitStatus > 0) {
          console.error(`Failure (Exit status: ${exitStatus})`)
        } else {
          console.log('Success')
        }
      })
      .catch(console.error)
    cb();
  },
  clean: async (cb) => {
    await rimraf("./public/slides");
    cb();
  },
  watch: (cb) => {
    watch("./docs/slides/**/*.md", marp.build);
    cb();
  }
}

exports.slides = series(marp.build);
```


## 既存のnpmタスクを統合する

既存のnpmタスクを統合することで、開発時に必要なタスクを一つのコマンドで実行できます。

パッケージをインストールします。

```
npm install gulp-prettier --save-dev
```

webpackのタスクを追加します。

```js

const webpack = {
  clean: async (cb) => {
    await rimraf("./public");
    cb();
  },
  build: (cb) => {
    const webpack = require("webpack");
    const webpackConfig = require("./webpack.config.js");
    webpack(webpackConfig, (err, stats) => {
      if (err || stats.hasErrors()) {
        console.error(err);
      }
      cb();
    });
  },
  watch: (cb) => {
    const webpack = require("webpack");
    const webpackConfig = require("./webpack.config.js");
    const compiler = webpack(webpackConfig);
    compiler.watch({}, (err, stats) => {
      if (err || stats.hasErrors()) {
        console.error(err);
      }
    });
    cb();
  },
  server: (cb) => {
    const webpack = require("webpack");
    const webpackConfig = require("./webpack.config.js");
    const compiler = webpack(webpackConfig);
    const WebpackDevServer = require("webpack-dev-server");
    const devServerOptions = Object.assign({}, webpackConfig.devServer, {
      open: false,
    });
    const server = new WebpackDevServer(compiler, devServerOptions);
    server.start(devServerOptions.port, devServerOptions.host, () => {
      console.log("Starting server on http://localhost:8080");
    });
    cb();
  },
}
```

jestのタスクを追加します。

```js
const jest = {
  test: (cb) => {
    const jest = require("jest");
    jest.run(["--coverage"]);
    cb();
  },
  watch: (cb) => {
    const jest = require("jest");
    jest.run(["--watch"]);
    cb();
  },
}
```

prettierのタスクを追加します。

```js
const prettier = {
  format: (cb) => {
    const prettier = require('gulp-prettier');
    return src("./src/**/*.{js,jsx,ts,tsx,json,css,scss,md}")
      .pipe(prettier({ singleQuote: true }))
      .pipe(dest('src'));
  },
  watch: (cb) => {
    watch("./src/**/*.{js,jsx,ts,tsx,json,css,scss,md}", prettier.format);
    cb();
  },
};

```

タスクをエクスポートします。

```js
const webpackBuildTasks = () => {
  return series(webpack.clean, webpack.build);
}

const asciidoctorBuildTasks = () => {
  return series(asciidoctor.clean, asciidoctor.build);
}

const marpBuildTasks = () => {
  return series(marp.clean, marp.build);
}

exports.default = series(
  webpackBuildTasks(),
  asciidoctorBuildTasks(),
  marpBuildTasks(),
  series(
    parallel(webpack.server, asciidoctor.server),
    parallel(webpack.watch, asciidoctor.watch, marp.watch),
    parallel(jest.watch)
  )
);

exports.build = series(
  webpackBuildTasks(),
  asciidoctorBuildTasks(),
  marpBuildTasks(),
  prettier.format
);

exports.test = series(jest.test);

exports.format = series(prettier.format);

exports.slides = series(marp.build);

exports.docs = series(
  asciidoctorBuildTasks(),
  marpBuildTasks(),
  parallel(asciidoctor.server, asciidoctor.watch, marp.watch),
);

exports.watch = parallel(webpack.watch, asciidoctor.watch, marp.watch, jest.watch);
```

package.jsonのscript以下の内容に変更します。

```json
{
  "scripts": {
    "start": "gulp",
    "build": "gulp build",
    "test": "gulp test",
    "docs": "gulp docs",
    "slides": "gulp slides",
    "watch": "gulp watch",
    "format": "gulp format"
  }
}
```

npmタスクからgulpのdefaultタスクを実行します。

```
npm start
```